import {
  courseWork,
  createAccountResponse,
  gradesType,
  subjectSchema,
} from "./types";

export const dataSubjects: subjectSchema[] = [
  {
    subjectId: "ENG101",
    subjectTitle: "English Language",
    level: "SS1",
  },
  {
    subjectId: "ENG200",
    subjectTitle: "English Language",
    level: "SS2",
  },
  {
    subjectId: "ENG302",
    subjectTitle: "English Language",
    level: "SS1",
  },
  {
    subjectId: "MTH100",
    subjectTitle: "Mathematics",
    level: "SS1",
  },
  {
    subjectId: "MTH200",
    subjectTitle: "Mathematics",
    level: "SS2",
  },
  {
    subjectId: "MTH300",
    subjectTitle: "Mathematics",
    level: "SS3",
  },

  {
    subjectId: "CHE00",
    subjectTitle: "Chemistry",
    level: "SS1",
  },
  {
    subjectId: "CHE200",
    subjectTitle: "Chemistry",
    level: "SS2",
  },
  {
    subjectId: "CHE300",
    subjectTitle: "Chemistry",
    level: "SS3",
  },
  {
    subjectId: "PHY100",
    subjectTitle: "Physics",
    level: "SS1",
  },
  {
    subjectId: "PHY200",
    subjectTitle: "Physics",
    level: "SS2",
  },
  {
    subjectId: "PHY300",
    subjectTitle: "Physics",
    level: "SS3",
  },
  {
    subjectId: "BIO100",
    subjectTitle: "Biology",
    level: "SS1",
  },
  {
    subjectId: "BIO200",
    subjectTitle: "Biology",
    level: "SS2",
  },
  {
    subjectId: "BIO300",
    subjectTitle: "Biology",
    level: "SS3",
  },
];

export const dataCourseWork: courseWork[] = [
  {
    lessonId: "eng101",
    lessonFile: "",
    lessonIndex: 0,
    lessonTopic: "Grammar",
    lessonVideo: "",
    level: "SS1",
    subjectId: "ENG101",
    term: 2,
  },
  {
    lessonId: "eng1s1",
    lessonFile: "",
    lessonIndex: 1,
    lessonTopic: "Oral English",
    lessonVideo: "",
    level: "SS1",
    subjectId: "ENG101",
    term: 2,
  },
  {
    lessonId: "eng112",
    lessonFile: "",
    lessonIndex: 2,
    lessonTopic: "Essay Writing",
    lessonVideo: "",
    level: "SS1",
    subjectId: "ENG101",
    term: 3,
  },
  {
    lessonId: "ef121",
    lessonFile: "",
    lessonIndex: 3,
    lessonTopic: "Figures of Speech",
    lessonVideo: "",
    level: "SS2",
    subjectId: "ENG200",
    term: 1,
  },
  {
    lessonId: "eng122",
    lessonFile: "",
    lessonIndex: 4,
    lessonTopic: "Summary",
    lessonVideo: "",
    level: "SS2",
    subjectId: "ENG200",
    term: 2,
  },
  {
    lessonId: "eng131",
    lessonFile: "",
    lessonIndex: 5,
    lessonTopic: "Comprehension",
    lessonVideo: "",
    level: "SS3",
    subjectId: "ENG302",
    term: 1,
  },
  {
    lessonId: "eng132",
    lessonFile: "",
    lessonIndex: 6,
    lessonTopic: "Singular & Plural",
    lessonVideo: "",
    level: "SS3",
    subjectId: "ENG302",
    term: 1,
  },
  {
    lessonId: "eng1351",
    lessonFile: "",
    lessonIndex: 7,
    lessonTopic: "Word Class",
    lessonVideo: "",
    level: "SS3",
    subjectId: "ENG302",
    term: 2,
  },
  {
    lessonId: "eng151",
    lessonFile: "",
    lessonIndex: 8,
    lessonTopic: "Clause & Sentence Construction",
    lessonVideo: "",
    level: "SS3",
    subjectId: "ENG302",
    term: 2,
  },
  {
    lessonId: "mth101",
    lessonFile: "",
    lessonIndex: 9,
    lessonTopic: "Basic Operations",
    lessonVideo: "",
    level: "SS1",
    subjectId: "MTH100",
    term: 1,
  },
  {
    lessonId: "mth102",
    lessonFile: "",
    lessonIndex: 0,
    lessonTopic: "Indices",
    lessonVideo: "",
    level: "SS1",
    subjectId: "MTH100",
    term: 1,
  },
  {
    lessonId: "mth103",
    lessonFile: "",
    lessonIndex: 0,
    lessonTopic: "Algebraic Expression",
    lessonVideo: "",
    level: "SS1",
    subjectId: "MTH100",
    term: 2,
  },
  {
    lessonId: "mth104",
    lessonFile: "",
    lessonIndex: 0,
    lessonTopic: "Circle Theorem",
    lessonVideo: "",
    level: "SS2",
    subjectId: "MTH200",
    term: 1,
  },
  {
    lessonId: "mth105",
    lessonFile: "",
    lessonIndex: 0,
    lessonTopic: "Quadratic Equation",
    lessonVideo: "",
    level: "SS2",
    subjectId: "MTH200",
    term: 2,
  },
  {
    lessonId: "mth106",
    lessonFile: "",
    lessonIndex: 0,
    lessonTopic: "Simultaneous Equation",
    lessonVideo: "",
    level: "SS2",
    subjectId: "MTH200",
    term: 2,
  },
  {
    lessonId: "mth107",
    lessonFile: "",
    lessonIndex: 0,
    lessonTopic: "Line Graph",
    lessonVideo: "",
    level: "SS2",
    subjectId: "MTH200",
    term: 3,
  },
  {
    lessonId: "mth108",
    lessonFile: "",
    lessonIndex: 0,
    lessonTopic: "Elevation & Depression",
    lessonVideo: "",
    level: "SS3",
    subjectId: "MTH300",
    term: 1,
  },
  {
    lessonId: "mth109",
    lessonFile: "",
    lessonIndex: 0,
    lessonTopic: "Arithmetic Progression & Geometric Progression",
    lessonVideo: "",
    level: "SS3",
    subjectId: "MTH300",
    term: 1,
  },
  {
    lessonId: "mth110",
    lessonFile: "",
    lessonIndex: 0,
    lessonTopic: "Longitude & Latitude",
    lessonVideo: "",
    level: "SS3",
    subjectId: "MTH300",
    term: 2,
  },
  {
    lessonId: "mth111",
    lessonFile: "",
    lessonIndex: 0,
    lessonTopic: "Geometric",
    lessonVideo: "",
    level: "SS3",
    subjectId: "MTH300",
    term: 2,
  },
  {
    lessonId: "mth112",
    lessonFile: "",
    lessonIndex: 0,
    lessonTopic: "Binomial Expansion",
    lessonVideo: "",
    level: "SS3",
    subjectId: "MTH300",
    term: 3,
  },
  {
    lessonId: "phy00",
    lessonFile: "",
    lessonIndex: 0,
    lessonTopic: "Fundamental Quantities",
    lessonVideo: "",
    level: "SS1",
    subjectId: "PHY100",
    term: 1,
  },
  {
    lessonId: "phy01",
    lessonFile: "",
    lessonIndex: 0,
    lessonTopic: "Charles Law",
    lessonVideo: "",
    level: "SS1",
    subjectId: "PHY100",
    term: 1,
  },
  {
    lessonId: "phy02",
    lessonFile: "",
    lessonIndex: 0,
    lessonTopic: "Boyels Law",
    lessonVideo: "",
    level: "SS1",
    subjectId: "PHY100",
    term: 2,
  },
  {
    lessonId: "phy03",
    lessonFile: "",
    lessonIndex: 0,
    lessonTopic: "Fluid & Thermodynamics",
    lessonVideo: "",
    level: "SS1",
    subjectId: "PHY100",
    term: 3,
  },
  {
    lessonId: "phy04",
    lessonFile: "",
    lessonIndex: 0,
    lessonTopic: "Force & Gravity",
    lessonVideo: "",
    level: "SS1",
    subjectId: "PHY100",
    term: 3,
  },
  {
    lessonId: "phy05",
    lessonFile: "",
    lessonIndex: 0,
    lessonTopic: "Principle of Equilibrium",
    lessonVideo: "",
    level: "SS2",
    subjectId: "PHY200",
    term: 1,
  },
  {
    lessonId: "phy06",
    lessonFile: "",
    lessonIndex: 0,
    lessonTopic: "Energy",
    lessonVideo: "",
    level: "SS2",
    subjectId: "PHY200",
    term: 2,
  },
  {
    lessonId: "phy07",
    lessonFile: "",
    lessonIndex: 0,
    lessonTopic: "Kinetic Energy",
    lessonVideo: "",
    level: "SS2",
    subjectId: "PHY200",
    term: 2,
  },
  {
    lessonId: "phy08",
    lessonFile: "",
    lessonIndex: 0,
    lessonTopic: "Wave",
    lessonVideo: "",
    level: "SS2",
    subjectId: "PHY200",
    term: 3,
  },
  {
    lessonId: "phy09",
    lessonFile: "",
    lessonIndex: 0,
    lessonTopic: "Electromagnetic Wave",
    lessonVideo: "",
    level: "SS3",
    subjectId: "PHY300",
    term: 1,
  },
  {
    lessonId: "phy10",
    lessonFile: "",
    lessonIndex: 0,
    lessonTopic: "Sound Wave",
    lessonVideo: "",
    level: "SS3",
    subjectId: "PHY300",
    term: 2,
  },
  {
    lessonId: "che10",
    lessonFile: "",
    lessonIndex: 0,
    lessonTopic: "Intro. to Chemistry",
    lessonVideo: "",
    level: "SS1",
    subjectId: "CHE00",
    term: 1,
  },
  {
    lessonId: "che20",
    lessonFile: "",
    lessonIndex: 0,
    lessonTopic: "Atom & Molecule",
    lessonVideo: "",
    level: "SS1",
    subjectId: "CHE00",
    term: 2,
  },
  {
    lessonId: "che30",
    lessonFile: "",
    lessonIndex: 0,
    lessonTopic: "Stochio-Chemistry",
    lessonVideo: "",
    level: "SS1",
    subjectId: "CHE00",
    term: 3,
  },
  {
    lessonId: "che40",
    lessonFile: "",
    lessonIndex: 0,
    lessonTopic: "Metals",
    lessonVideo: "",
    level: "SS2",
    subjectId: "CHE200",
    term: 1,
  },
  {
    lessonId: "che50",
    lessonFile: "",
    lessonIndex: 0,
    lessonTopic: "Non-Metals",
    lessonVideo: "",
    level: "SS2",
    subjectId: "CHE200",
    term: 2,
  },
  {
    lessonId: "che60",
    lessonFile: "",
    lessonIndex: 0,
    lessonTopic: "Metalloid",
    lessonVideo: "",
    level: "SS2",
    subjectId: "CHE200",
    term: 2,
  },
  {
    lessonId: "che70",
    lessonFile: "",
    lessonIndex: 0,
    lessonTopic: "Organic Chemistry",
    lessonVideo: "",
    level: "SS2",
    subjectId: "CHE200",
    term: 3,
  },
  {
    lessonId: "che80",
    lessonFile: "",
    lessonIndex: 0,
    lessonTopic: "Electrolysis & Electrolytes",
    lessonVideo: "",
    level: "SS3",
    subjectId: "CHE300",
    term: 1,
  },
  {
    lessonId: "bio001",
    lessonFile: "",
    lessonIndex: 0,
    lessonTopic: "Living Things & Non-Living Things",
    lessonVideo: "",
    level: "SS1",
    subjectId: "BIO100",
    term: 1,
  },
  {
    lessonId: "bio002",
    lessonFile: "",
    lessonIndex: 0,
    lessonTopic: "Taxonomy",
    lessonVideo: "",
    level: "SS1",
    subjectId: "BIO100",
    term: 2,
  },
  {
    lessonId: "bio003",
    lessonFile: "",
    lessonIndex: 0,
    lessonTopic: "Ecosystem & Ecology",
    lessonVideo: "",
    level: "SS1",
    subjectId: "BIO100",
    term: 3,
  },
  {
    lessonId: "bio004",
    lessonFile: "",
    lessonIndex: 0,
    lessonTopic: "Bone & Cartilage",
    lessonVideo: "",
    level: "SS2",
    subjectId: "BIO200",
    term: 1,
  },
  {
    lessonId: "bio05",
    lessonFile: "",
    lessonIndex: 0,
    lessonTopic: "Digestive System",
    lessonVideo: "",
    level: "SS2",
    subjectId: "BIO200",
    term: 2,
  },
  {
    lessonId: "bio006",
    lessonFile: "",
    lessonIndex: 0,
    lessonTopic: "Transportation System",
    lessonVideo: "",
    level: "SS2",
    subjectId: "BIO200",
    term: 3,
  },
  {
    lessonId: "bio007",
    lessonFile: "",
    lessonIndex: 0,
    lessonTopic: "Internal Regulatory System",
    lessonVideo: "",
    level: "SS3",
    subjectId: "BIO300",
    term: 1,
  },
  {
    lessonId: "bio008",
    lessonFile: "",
    lessonIndex: 0,
    lessonTopic: "The Brain",
    lessonVideo: "",
    level: "SS3",
    subjectId: "BIO300",
    term: 2,
  },
  {
    lessonId: "bio009",
    lessonFile: "",
    lessonIndex: 0,
    lessonTopic: "Sensory Organs",
    lessonVideo: "",
    level: "SS3",
    subjectId: "BIO300",
    term: 1,
  },
];

export const users: createAccountResponse[] = [
  {
    success: true,
    data: {
      activation_token: "",
      message: "",
      user: {
        user_uuid: "stu001",
        email: "mbakajohpaul@gmail.com",
        role: "STUDENT",
        status: "active",
        salutation: "Master",
        first_name: "JohnPaul",
        last_name: "Mbaka",
        phone: "+2349133950084",
        profile_picture: "",
        student_id: "stu001",
        teacher_id: 0,
        currentLevel: "SS1",
        gender: "Male",
        email_verified: false,
        last_login: "",
        created_by: "",
        created_at: "",
        updated_at: "",
        updated_by: "",
      },
    },
  },
  {
    success: true,
    data: {
      activation_token: "",
      message: "",
      user: {
        user_uuid: "stu002",
        email: "mbakajohpaul@gmail.com",
        role: "STUDENT",
        status: "active",
        salutation: "Mrs.",
        first_name: "Celine",
        last_name: "Okorafor",
        phone: "+2349133950084",
        profile_picture: "",
        student_id: "stu002",
        teacher_id: 0,
        currentLevel: "SS2",
        gender: "Female",
        email_verified: false,
        last_login: "",
        created_by: "",
        created_at: "",
        updated_at: "",
        updated_by: "",
      },
    },
  },
  {
    success: true,
    data: {
      activation_token: "",
      message: "",
      user: {
        user_uuid: "stu003",
        email: "mbakajohpaul@gmail.com",
        role: "STUDENT",
        status: "active",
        salutation: "Miss",
        first_name: "Omolara",
        last_name: "Balogun",
        phone: "+2349133950084",
        profile_picture: "",
        student_id: "stu001",
        teacher_id: 0,
        currentLevel: "SS1",
        gender: "Female",
        email_verified: false,
        last_login: "",
        created_by: "",
        created_at: "",
        updated_at: "",
        updated_by: "",
      },
    },
  },
  {
    success: true,
    data: {
      activation_token: "",
      message: "",
      user: {
        user_uuid: "stu004",
        email: "mbakajohpaul@gmail.com",
        role: "STUDENT",
        status: "active",
        salutation: "Master",
        first_name: "JohnPaul Chidera",
        last_name: "Mbaka",
        phone: "+2349133950084",
        profile_picture: "",
        student_id: "stu004",
        teacher_id: 0,
        currentLevel: "SS3",
        gender: "Male",
        email_verified: false,
        last_login: "",
        created_by: "",
        created_at: "",
        updated_at: "",
        updated_by: "",
      },
    },
  },
  {
    success: true,
    data: {
      activation_token: "",
      message: "",
      user: {
        user_uuid: "stu005",
        email: "mbakajohpaul@gmail.com",
        role: "STUDENT",
        status: "active",
        salutation: "Master",
        first_name: "Nnamdi",
        last_name: "Anthony",
        phone: "+2349133950084",
        profile_picture: "",
        student_id: "stu005",
        teacher_id: 0,
        currentLevel: "SS3",
        gender: "Male",
        email_verified: false,
        last_login: "",
        created_by: "",
        created_at: "",
        updated_at: "",
        updated_by: "",
      },
    },
  },
  {
    success: true,
    data: {
      activation_token: "",
      message: "",
      user: {
        user_uuid: "stu006",
        email: "mbakajohpaul@gmail.com",
        role: "STUDENT",
        status: "active",
        salutation: "Master",
        first_name: "Onyinyechi",
        last_name: "Gift",
        phone: "+2349133950084",
        profile_picture: "",
        student_id: "stu006",
        teacher_id: 0,
        currentLevel: "SS3",
        gender: "Female",
        email_verified: false,
        last_login: "",
        created_by: "",
        created_at: "",
        updated_at: "",
        updated_by: "",
      },
    },
  },
];

export const records: gradesType[] = [
  {
    gradeId: "grd000",
    userId: "stu001",
    subjects: [
      {
        ca: [
          { score: 10, total: 10, title: "CA1" },
          { score: 8, total: 10, title: "CA1" },
          { score: 3, total: 10, title: "CA1" },
          { score: 9, total: 10, title: "CA1" },
        ],
        exam: { score: 50, total: 100, title: "exam" },
        gradeAverage: 0.0,
        position: 8,
        highestGrade: 0,
        lowestGrade: 0,
        term: 1,
        level: "SS1",
        session: "",
        subjectId: "MTH100",
      },
    ],
    studentTotal: 0,
    classAverage: 0.0,
    classPosition: 2,
    session: "2023/2024",
  },
  {
    gradeId: "grd000",
    userId: "stu001",
    subjects: [
      {
        ca: [
          { score: 10, total: 10, title: "CA1" },
          { score: 8, total: 10, title: "CA1" },
          { score: 3, total: 10, title: "CA1" },
          { score: 9, total: 10, title: "CA1" },
        ],
        exam: { score: 50, total: 100, title: "exam" },
        gradeAverage: 0.0,
        position: 8,
        highestGrade: 0,
        lowestGrade: 0,
        term: 1,
        level: "SS2",
        session: "",
        subjectId: "CHE200",
      },
    ],
    studentTotal: 0,
    classAverage: 0.0,
    classPosition: 2,
    session: "2024/2025",
  },
  {
    gradeId: "grd000",
    userId: "stu001",
    subjects: [
      {
        ca: [
          { score: 10, total: 10, title: "CA1" },
          { score: 8, total: 10, title: "CA1" },
          { score: 3, total: 10, title: "CA1" },
          { score: 9, total: 10, title: "CA1" },
        ],
        exam: { score: 50, total: 100, title: "exam" },
        gradeAverage: 0.0,
        position: 8,
        highestGrade: 0,
        lowestGrade: 0,
        term: 1,
        level: "SS1",
        session: "",
        subjectId: "ENG101",
      },
    ],
    studentTotal: 0,
    classAverage: 0.0,
    classPosition: 2,
    session: "2023/2024",
  },
];
